import { DownloadOutlined, CopyOutlined, LinkOutlined, SearchOutlined } from "@ant-design/icons";
import { Button, Card, Input, Select, Space, Table, Tag, message } from "antd";
import { useCallback, useEffect, useState } from "react";
import { authorizedFetch, autoDashboardApi } from "../../api/backend";
export default function CandidateDetailTable({ dashboardId, suppliers }: { dashboardId: string; suppliers: string[] }) {
  const [rows, setRows] = useState<any[]>([]), [total, setTotal] = useState(0), [page, setPage] = useState(1), [loading, setLoading] = useState(false);
  const [filters, setFilters] = useState<Record<string, string>>({});
  const query = useCallback((target = 1) => { const params = new URLSearchParams({ page: String(target), pageSize: "20" }); Object.entries(filters).forEach(([k, v]) => v && params.set(k, v)); setLoading(true); autoDashboardApi.section<any>(dashboardId, "candidates", `?${params}`).then((data) => { setRows(data.rows); setTotal(data.pagination.total); setPage(target); }).catch((e) => message.error(e.message)).finally(() => setLoading(false)); }, [dashboardId, filters]);
  useEffect(() => { void query(1); }, [query]);
  const set = (name: string, value?: string) => setFilters((old) => ({ ...old, [name]: value || "" }));
  const exportRows = async () => { const params = new URLSearchParams({ ...filters, export: "xlsx" }); const response = await authorizedFetch(`/api/auto-dashboard/${dashboardId}/candidates?${params}`); if (!response.ok) return message.error("导出失败"); const url = URL.createObjectURL(await response.blob()), a = document.createElement("a"); a.href = url; a.download = "招聘候选人明细.xlsx"; a.click(); URL.revokeObjectURL(url); };
  return <Card title="候选人明细" extra={<Button icon={<DownloadOutlined />} onClick={() => void exportRows()}>Excel 导出</Button>}><Space wrap className="candidate-filters"><Input allowClear prefix={<SearchOutlined />} placeholder="搜索姓名" onChange={(e) => set("keyword", e.target.value)} /><Select allowClear placeholder="供应商" options={suppliers.map((value) => ({ value }))} onChange={(v) => set("supplier", v)} /><Select allowClear placeholder="业务方向" options={["视频", "音频", "未知"].map((value) => ({ value }))} onChange={(v) => set("businessType", v)} /><Select allowClear placeholder="面试结果" options={["通过", "不通过", "待反馈", "取消", "未知"].map((value) => ({ value }))} onChange={(v) => set("interviewResult", v)} /><Select allowClear placeholder="入职状态" options={["已入职", "待入职", "已放弃", "已离职", "未知"].map((value) => ({ value }))} onChange={(v) => set("entryStatus", v)} /></Space><Table rowKey="id" loading={loading} dataSource={rows} pagination={{ current: page, pageSize: 20, total, showSizeChanger: false, showTotal: (n) => `共 ${n} 条`, onChange: query }} scroll={{ x: 1700 }} columns={[{ title: "候选人", dataIndex: "name", fixed: "left" }, { title: "供应商", dataIndex: "supplier" }, { title: "业务方向", dataIndex: "businessType", render: (v) => <Tag>{v}</Tag> }, { title: "面试时间", dataIndex: "interviewTimeRaw" }, { title: "腾讯会议", render: (_v, r) => r.meetingUrl ? <a href={r.meetingUrl} target="_blank"><LinkOutlined /> 加入</a> : r.meetingCode ? <Button size="small" type="link" icon={<CopyOutlined />} onClick={() => { void navigator.clipboard?.writeText(r.meetingCode); message.success("会议号已复制"); }}>{r.meetingCode}</Button> : "—" }, { title: "面试结果", dataIndex: "interviewResult" }, { title: "定级", dataIndex: "level" }, { title: "面试官", dataIndex: "interviewer" }, { title: "面评", dataIndex: "interviewComment", ellipsis: true }, { title: "入职日期", dataIndex: "entryDate", render: (v) => v?.slice(0, 10) || "—" }, { title: "入职状态", dataIndex: "entryStatus" }, { title: "来源工作表", dataIndex: "sourceSheet" }]} /></Card>;
}
