import crypto from "node:crypto";
import { createKimClient } from "./kimClient.mjs";

const id = () => crypto.randomUUID();
const fmt = (value) => value ? new Date(value).toLocaleString("zh-CN", { timeZone: process.env.KIM_TIMEZONE || "Asia/Shanghai", hour12: false }) : "—";
export const defaultReminderSettings = { enabled: true, notifyOnCreated: true, notifyOnChanged: true, notifyOnCancelled: true, reminder24Hours: true, reminder2Hours: true, reminder30Minutes: false, feedbackReminder: true, overdueFeedbackReminder: true };
export function buildMessage(interview, type) { const base = `候选人：${interview.candidateName}\n岗位：${interview.position}\n轮次：${interview.roundName}\n时间：${fmt(interview.startTime)}\n面试官：${interview.interviewer}\n方式：${interview.interviewType}`; const link = interview.meetingUrl ? `\n会议链接：${interview.meetingUrl}` : interview.location ? `\n地点：${interview.location}` : ""; const prefix = { created: "## 面试安排通知", before_24_hours: "## 面试前24小时提醒", before_2_hours: "## 面试前2小时提醒", before_30_minutes: "## 面试前30分钟提醒", changed: "## 面试安排已变更", cancelled: "## 面试已取消", feedback_pending: "## 面试结果待反馈", feedback_overdue: "## 面评超时催办", candidate_no_show: "## 候选人未到场" }[type] || "## 面试提醒"; return `${prefix}\n\n${base}${link}\n\n请及时处理。`; }
export function createInterviewReminderTasks(interview, now = new Date()) { const settings = { ...defaultReminderSettings, ...(interview.reminderSettings || {}) }; if (!settings.enabled) return []; const start = new Date(interview.startTime).getTime(); const current = new Date(now).getTime(); const nodes = []; const add = (type, when) => { const key = `interview:${interview.id}:${type}:${interview.startTime}`; nodes.push({ id: id(), interviewId: interview.id, candidateId: interview.candidateId, type, scheduledAt: new Date(when).toISOString(), status: when <= current ? "skipped" : "pending", targetType: "group", targetMasked: "招聘群", idempotencyKey: key, attemptCount: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); }; if (settings.notifyOnCreated) add("created", current + 1000); if (settings.reminder24Hours && start - 86400000 > current) add("before_24_hours", start - 86400000); if (settings.reminder2Hours && start - 7200000 > current) add("before_2_hours", start - 7200000); if (settings.reminder30Minutes && start - 1800000 > current) add("before_30_minutes", start - 1800000); return nodes; }
export async function scanAndSendInterviewReminders(store, env = process.env) { const kim = createKimClient(env); const now = Date.now(); for (const task of store.tasks.filter((item) => item.status === "pending" && new Date(item.scheduledAt).getTime() <= now)) { task.status = "processing"; task.attemptCount += 1; task.lastAttemptAt = new Date().toISOString(); const interview = store.interviews.find((item) => item.id === task.interviewId); if (!interview || interview.status === "已取消" || interview.status === "未到场") { task.status = "cancelled"; continue; } const result = await kim.sendMessage({}, { type: "markdown", title: "Kim面试提醒", content: buildMessage(interview, task.type) }, { idempotencyKey: task.idempotencyKey }); task.status = result.success ? "success" : task.attemptCount >= 3 ? "failed" : "pending"; task.sentAt = result.success ? result.sentAt : undefined; task.failureReason = result.success ? undefined : result.message; store.logs.unshift({ id: id(), interviewId: interview.id, reminderTaskId: task.id, scene: "interview_reminder", reminderType: task.type, recipientType: "kim_group", recipientMasked: "招聘群", title: "Kim面试提醒", contentDigest: crypto.createHash("sha256").update(buildMessage(interview, task.type)).digest("hex").slice(0, 16), status: result.success ? "success" : "failed", attemptCount: task.attemptCount, createdAt: new Date().toISOString(), sentAt: result.success ? result.sentAt : undefined }); } }
