export type ResumeResult = "待筛选" | "通过" | "不通过";
export type InterviewResult = "待面试" | "待反馈" | "通过" | "不通过" | "未到场";
export type CandidateStatus = "简历待筛选" | "简历未通过" | "待安排面试" | "待面试" | "面试待反馈" | "面试未通过" | "面试通过" | "待确认入职" | "待入职" | "培训中" | "培训未通过" | "项目中" | "候选人放弃" | "已离职" | "异常";
export interface TimelineItem { time: string; action: string; operator: string; remark?: string }
export interface CandidateRemark { id: string; content: string; createdAt: string; createdBy: string }
export interface CandidateStatusEvent { id:string; candidateId:string; status:CandidateStatus; effectiveAt:string; operator:string; source:"系统"|"招聘人员"|"项目人员"|"供应商"; remark?:string }
export interface InterviewRecord { id:string; candidateId:string; round:number; roundName:string; interviewer:string; scheduledAt:string; completedAt?:string; meetingType:"腾讯会议"|"现场面试"|"电话面试"; meetingUrl?:string; result:"待确认"|"待面试"|"待反馈"|"通过"|"不通过"|"未到场"|"已取消"; score?:number; comment?:string; createdAt:string; updatedAt:string }
export interface OperationLog { id:string; candidateId?:string; module:"候选人"|"面试"|"Offer"|"入职"|"培训"|"项目"|"备注"|"系统"; action:string; field?:string; oldValue?:string; newValue?:string; operator:string; operatedAt:string; reason?:string; isForcedAdjustment?:boolean }
export interface DuplicateCandidateResult { isDuplicate:boolean; level:"无"|"疑似重复"|"确定重复"; matchedCandidateIds:string[]; reasons:string[] }
export interface Candidate { id:string; name:string; phone:string; idCardMasked?:string; vendor:string; project:string; position:string; resumeSubmitDate:string; resumeResult:ResumeResult; resumeFeedbackDate?:string; interviewScheduled:boolean; interviewDate?:string; interviewRound?:string; interviewer?:string; interviewResult?:InterviewResult; interviewFeedbackDate?:string; interviewComment?:string; interviews:InterviewRecord[]; offerConfirmed:boolean; offerConfirmedDate?:string; originalExpectedEntryDate?:string; expectedEntryDate?:string; actualEntryDate?:string; trainingStartDate?:string; trainingCompletedDate?:string; projectStartDate?:string; leaveDate?:string; currentStatus:CandidateStatus; giveUpReason?:string; abnormalReason?:string; updatedAt:string; updatedBy:string; timeline:TimelineItem[]; remarks?:CandidateRemark[]; statusEvents:CandidateStatusEvent[]; operationLogs:OperationLog[]; duplicateCheck?:DuplicateCandidateResult }
