import { useEffect, useMemo, useState } from "react";
import { Alert, Badge, Button, Card, Descriptions, Divider, Drawer, Empty, Input, List, Modal, Progress, Select, Space, Statistic, Table, Tabs, Tag, Typography, Upload, message } from "antd";
import * as mammoth from "mammoth";
import * as pdfjsLib from "pdfjs-dist/legacy/build/pdf.mjs";
import { CheckCircleOutlined, FileSearchOutlined, LeftOutlined, UploadOutlined } from "@ant-design/icons";
import type { Candidate } from "../types/recruitment";
import type { JobDescription, ResumeFileRecord, ResumeProfile, ResumeReviewStatus } from "../types/resumeScreening";
import { createMockResumes, defaultJobs, detectResumeDuplicates, extractProfile, ruleBasedJobMatch } from "../utils/resumeScreening";
import { exportResumeScreeningExcel } from "../utils/resumeScreeningExport";
import { authorizedFetch } from "../api/backend";

type Props = { onBack: () => void; onTransfer: (candidate: Candidate) => void };
const riskColor: Record<string, string> = { 无重复: "green", 同名不同人: "blue", 疑似重复: "orange", 高度疑似重复: "red", 确定重复: "red", 需人工复核: "gold" };
const reviewColor: Record<string, string> = { 待复核: "orange", 简历通过: "green", 待补充信息: "gold", 暂缓: "default", 简历不通过: "red" };

async function readResumeText(file: File): Promise<string> {
  if (file.type.startsWith("text/")) return file.text();
  const buffer = await file.arrayBuffer();
  if (/\.docx?$/i.test(file.name)) {
    const result = await mammoth.extractRawText({ arrayBuffer: buffer });
    return result.value;
  }
  if (/\.pdf$/i.test(file.name)) {
    const document = await pdfjsLib.getDocument({ data: new Uint8Array(buffer), disableWorker: true } as never).promise;
    const pages: string[] = [];
    for (let pageNumber = 1; pageNumber <= document.numPages; pageNumber += 1) {
      const page = await document.getPage(pageNumber);
      const content = await page.getTextContent();
      pages.push(content.items.map((item) => "str" in item ? item.str : "").join(" "));
    }
    return pages.join("\n");
  }
  return "";
}

function createPendingProfile(file: File, id: string): ResumeProfile {
  return { id: `RP-${id}`, fileId: id, name: file.name.replace(/\.(pdf|docx?|png|jpe?g)$/i, "") || "待识别候选人", universities: [], skills: [], certificates: [], rawText: "", extractedAt: "", extractionSource: "rule", extractionConfidence: 0, missingFields: ["大学", "专业"], warnings: ["尚未开始解析"] };
}

export default function ResumeScreeningPage({ onBack, onTransfer }: Props) {
  const [records, setRecords] = useState<ResumeFileRecord[]>(createMockResumes);
  const [jobs, setJobs] = useState<JobDescription[]>(defaultJobs);
  const [jobId, setJobId] = useState(defaultJobs[0].id);
  const [selected, setSelected] = useState<ResumeFileRecord | null>(null);
  const [search, setSearch] = useState("");
  const [reviewFilter, setReviewFilter] = useState("全部");
  const [jobModal, setJobModal] = useState(false);
  const [jobText, setJobText] = useState("");
  const [checked, setChecked] = useState<string[]>([]);
  const [aiConfigured, setAiConfigured] = useState(false);
  const [pendingFiles, setPendingFiles] = useState<Record<string, File>>({});
  useEffect(() => { authorizedFetch("/api/ai/status").then((response) => response.json()).then((body: { data?: { configured?: boolean } }) => setAiConfigured(Boolean(body.data?.configured))).catch(() => setAiConfigured(false)); }, []);
  const job = jobs.find((item) => item.id === jobId) || jobs[0];
  const visible = useMemo(() => records.filter((r) => (!search || `${r.profile.name}${r.profile.university || ""}${r.vendor}`.includes(search)) && (reviewFilter === "全部" || r.manualReviewStatus === reviewFilter)), [records, search, reviewFilter]);
  const stats = { uploaded: records.length, parsed: records.filter((r) => r.parseStatus === "解析成功").length, same: records.filter((r) => r.duplicate.level === "同名不同人").length, duplicate: records.filter((r) => ["疑似重复", "高度疑似重复", "确定重复", "需人工复核"].includes(r.duplicate.level)).length, high: records.filter((r) => (r.match?.overallScore || 0) >= 80).length, pending: records.filter((r) => r.manualReviewStatus === "待复核").length, failed: records.filter((r) => r.parseStatus !== "解析成功").length };
  const refreshDuplicates = (next: ResumeFileRecord[]) => next.map((record) => ({ ...record, duplicate: detectResumeDuplicates(record.profile, next.map((item) => item.profile)) }));
  const addFiles = async (fileList: File[]) => {
    if (records.length + fileList.length > 100) return message.error("单次最多保留100份简历");
    const allowed = /\.(pdf|docx?|png|jpe?g)$/i;
    const additions: ResumeFileRecord[] = [];
    for (const file of fileList) {
      if (file.size > 15 * 1024 * 1024) { message.error(`${file.name} 超过15MB，已跳过`); continue; }
      if (!allowed.test(file.name)) { message.error(`${file.name} 格式不支持，已跳过`); continue; }
      let raw = ""; try { raw = await readResumeText(file); } catch { raw = ""; }
      if (!raw.trim()) raw = `姓名：${file.name.split(/[._-]/)[0]}\n简历文本暂未提取，请在详情中人工补充大学和专业。`;
      const id = `RF-UP-${Date.now()}-${additions.length}`; const profile = extractProfile(file.name, raw, "人瑞");
      additions.push({ id, originalFileName: file.name, fileType: file.type || "application/octet-stream", fileSize: file.size, fileHash: `${file.name}-${file.size}-${file.lastModified}`, vendor: "人瑞", targetJobId: jobId, parseStatus: file.type.startsWith("image/") || raw.includes("简历文本暂未提取") ? "需人工处理" : "解析成功", aiStatus: "未筛选", manualReviewStatus: "待复核", uploadedAt: new Date().toLocaleString("zh-CN", { hour12: false }), profile, duplicate: { resumeId: profile.id, level: "无重复", score: 0, matchedResumeIds: [], reasons: [], differences: [], requiresManualReview: false } });
    }
    if (additions.length) { setRecords((current) => refreshDuplicates([...additions, ...current])); message.success(`已上传 ${additions.length} 份简历`); }
  };
  const runMatch = async (ids = visible.map((r) => r.id)) => { const targets = await Promise.all(records.filter((record) => ids.includes(record.id)).map(async (record) => { const file = pendingFiles[record.id]; if (record.parseStatus !== "待解析" || !file) return record; let raw = ""; try { raw = await readResumeText(file); } catch { raw = ""; } if (!raw.trim()) raw = `姓名：${file.name.split(/[._-]/)[0]}\\n简历正文暂未提取，请人工补充大学和专业。`; const profile = extractProfile(file.name, raw, "人瑞"); return { ...record, profile, parseStatus: raw.includes("简历正文暂未提取") ? "解析失败" as const : "解析成功" as const }; })); setRecords((current) => current.map((r) => { const parsed = targets.find((item) => item.id === r.id); return ids.includes(r.id) ? { ...(parsed || r), aiStatus: "筛选中" as const, targetJobId: job.id } : r; })); let aiCount = 0; const results = await Promise.all(targets.map(async (record) => { try { const response = await authorizedFetch("/api/ai/resume-match", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ resume: record.profile, job }) }); if (!response.ok) throw new Error("AI unavailable"); const body = await response.json() as { data?: ResumeFileRecord["match"] }; if (!body.data) throw new Error("AI result empty"); aiCount += 1; return { id: record.id, match: body.data, aiStatus: "筛选成功" as const }; } catch { return { id: record.id, match: ruleBasedJobMatch(record.profile, job), aiStatus: "筛选成功" as const }; } })); setRecords((current) => current.map((record) => { const result = results.find((item) => item.id === record.id); return result ? { ...record, ...result, targetJobId: job.id } : record; })); message.info(aiCount ? `已完成筛选：${aiCount} 份使用 AI，${targets.length - aiCount} 份使用规则兜底` : "AI接口调用失败（鉴权或网络错误），已使用规则筛选兜底；请检查服务端 AI_PROVIDER、AI_BASE_URL 和 AI_API_KEY"); };
  const review = (status: ResumeReviewStatus, note: string) => { if (!selected) return; if (status === "简历不通过" && !note.trim()) return message.error("标记不通过必须填写原因"); const next = records.map((r) => r.id === selected.id ? { ...r, manualReviewStatus: status, manualNote: note } : r); setRecords(next); setSelected(next.find((r) => r.id === selected.id) || null); message.success("人工复核结果已保存"); };
  const transfer = () => { if (!selected || selected.manualReviewStatus !== "简历通过") return message.warning("请先人工确认简历通过"); if (selected.duplicate.level === "确定重复") return message.error("确定重复的简历不能重复建档"); const p = selected.profile; const candidate: Candidate = { id: `C-AI-${selected.id}`, name: p.name, phone: p.phone || "", vendor: selected.vendor, project: job.projectName, position: job.jobName, resumeSubmitDate: new Date().toISOString().slice(0, 10), resumeResult: "通过", resumeFeedbackDate: new Date().toISOString().slice(0, 10), interviewScheduled: false, interviews: [], offerConfirmed: false, currentStatus: "待安排面试", updatedAt: new Date().toLocaleString("zh-CN", { hour12: false }), updatedBy: "AI筛选转入", timeline: [{ time: new Date().toLocaleString("zh-CN", { hour12: false }), action: "AI简历筛选人工确认通过，流转候选人流程", operator: "招聘人员", remark: selected.manualNote }], statusEvents: [{ id: `SE-AI-${selected.id}`, candidateId: `C-AI-${selected.id}`, status: "待安排面试", effectiveAt: new Date().toISOString(), operator: "招聘人员", source: "招聘人员", remark: "AI筛选人工确认通过" }], operationLogs: [{ id: `LOG-AI-${selected.id}`, candidateId: `C-AI-${selected.id}`, module: "候选人", action: "AI简历筛选通过并流转候选人流程", operator: "招聘人员", operatedAt: new Date().toLocaleString("zh-CN", { hour12: false }), reason: selected.manualNote }] }; onTransfer(candidate); message.success("已流转到候选人管理"); };
  const columns = [{ title: "候选人", render: (_: unknown, r: ResumeFileRecord) => <a onClick={() => setSelected(r)}>{r.profile.name}</a> }, { title: "大学", render: (_: unknown, r: ResumeFileRecord) => r.profile.university || "—" }, { title: "专业", render: (_: unknown, r: ResumeFileRecord) => r.profile.major || "—" }, { title: "简历文件", dataIndex: "originalFileName", ellipsis: true }, { title: "解析状态", render: (_: unknown, r: ResumeFileRecord) => <Tag color={r.parseStatus === "解析成功" ? "green" : "orange"}>{r.parseStatus}</Tag> }, { title: "重复风险", render: (_: unknown, r: ResumeFileRecord) => <Tag color={riskColor[r.duplicate.level]}>{r.duplicate.level}</Tag> }, { title: "JD匹配", render: (_: unknown, r: ResumeFileRecord) => r.match ? <><b>{r.match.overallScore}</b> 分 <Tag color={r.match.recommendation === "推荐通过" ? "green" : "orange"}>{r.match.recommendation}</Tag></> : "未筛选" }, { title: "人工复核", render: (_: unknown, r: ResumeFileRecord) => <Tag color={reviewColor[r.manualReviewStatus]}>{r.manualReviewStatus}</Tag> }];
  return <div className="content screening-page"><Space className="screening-header" align="start"><Button icon={<LeftOutlined />} onClick={onBack}>返回招聘看板</Button><div><Typography.Title level={3} style={{ margin: 0 }}>AI 简历筛选与岗位匹配</Typography.Title><Typography.Text type="secondary">AI 结果仅作为招聘辅助依据，最终判断由招聘人员完成。</Typography.Text></div><Space><Upload accept=".pdf,.doc,.docx,.png,.jpg,.jpeg" showUploadList={false} beforeUpload={(file) => { void addFiles([file]); return false; }}><Button icon={<UploadOutlined />}>上传简历</Button></Upload><Button type="primary" disabled={!records.length} onClick={() => runMatch()}>AI开始筛选</Button><Button onClick={() => { setRecords(createMockResumes()); setPendingFiles({}); setSelected(null); setChecked([]); setSearch(""); setReviewFilter("全部"); message.success("已回到简历上传起始步骤"); }}>重新开始</Button><Button onClick={() => exportResumeScreeningExcel(visible, job)}>导出结果</Button></Space></Space><Alert type={aiConfigured ? "success" : "info"} showIcon message={aiConfigured ? "AI 模型已配置，将优先使用 AI 分析；失败时自动使用规则兜底。" : "AI 模型尚未配置，当前使用规则筛选兜底。"} description="AI 结果仅作为招聘辅助依据，不会自动淘汰候选人。" style={{ marginBottom: 18 }} />
    <Card className="screening-toolbar"><Space wrap><Select value={jobId} onChange={setJobId} style={{ width: 220 }} options={jobs.filter((j) => j.status === "启用").map((j) => ({ label: j.jobName, value: j.id }))} /><Upload accept=".pdf,.doc,.docx,.png,.jpg,.jpeg" multiple showUploadList={false} beforeUpload={(file, list) => { if (file === list[list.length - 1]) void addFiles(list); return false; }}><Button icon={<UploadOutlined />}>批量上传</Button></Upload><Button onClick={() => setJobModal(true)}>岗位 JD 管理</Button><Button disabled={!checked.length} onClick={() => runMatch(checked)}>批量筛选（{checked.length}）</Button><Select value={reviewFilter} onChange={setReviewFilter} style={{ width: 140 }} options={["全部", "待复核", "简历通过", "待补充信息", "暂缓", "简历不通过"].map((x) => ({ label: x, value: x }))} /><Input placeholder="搜索姓名、大学、供应商" value={search} onChange={(e) => setSearch(e.target.value)} style={{ width: 220 }} /></Space></Card>
    <div className="metric-grid screening-stat-grid">{[["已上传", stats.uploaded], ["解析成功", stats.parsed], ["同名候选人", stats.same], ["疑似重复", stats.duplicate], ["高匹配", stats.high], ["待人工复核", stats.pending], ["解析失败/待处理", stats.failed]].map(([title, value]) => <Card key={title as string}><Statistic title={title as string} value={value as number} /></Card>)}</div>
    <Card title="简历筛选结果" extra={<Badge count={visible.length} showZero />}><Table rowKey="id" rowSelection={{ selectedRowKeys: checked, onChange: (keys) => setChecked(keys as string[]) }} columns={columns} dataSource={visible} pagination={{ pageSize: 10 }} scroll={{ x: 1100 }} locale={{ emptyText: <Empty description="暂无简历，请上传文件" /> }} /></Card>
    <Drawer title={selected ? `${selected.profile.name} · 简历筛选详情` : "简历详情"} width={620} open={Boolean(selected)} onClose={() => setSelected(null)}>{selected && <Tabs items={[{ key: "base", label: "结构化信息", children: <Descriptions bordered column={1} size="small" items={[{ key: "phone", label: "手机号", children: selected.profile.phoneMasked || "—" }, { key: "school", label: "大学", children: selected.profile.university || "—" }, { key: "major", label: "专业", children: selected.profile.major || "—" }, { key: "education", label: "学历", children: selected.profile.highestEducation || "—" }, { key: "year", label: "毕业年份", children: selected.profile.graduationYear || "—" }, { key: "skills", label: "技能", children: selected.profile.skills.join("、") || "—" }]} /> }, { key: "raw", label: "简历原文", children: <Input.TextArea value={selected.profile.rawText} rows={14} readOnly /> }, { key: "duplicate", label: "同名与重复", children: <><Alert type={selected.duplicate.requiresManualReview ? "warning" : "info"} message={`${selected.duplicate.level}（${selected.duplicate.score}分）`} description={<>{selected.duplicate.reasons.map((x) => <div key={x}>{x}</div>)}{selected.duplicate.differences.map((x) => <div key={x}>差异：{x}</div>)}</>} /><Divider /><List size="small" dataSource={records.filter((r) => selected.duplicate.matchedResumeIds.includes(r.profile.id))} renderItem={(r) => <List.Item>{r.profile.name}｜{r.profile.university || "大学缺失"}｜{r.profile.major || "专业缺失"}｜{r.profile.phoneMasked || "—"}</List.Item>} /></> }, { key: "match", label: "JD 匹配分析", children: selected.match ? <><Progress type="circle" percent={selected.match.overallScore} /><Tag color={selected.match.recommendation === "推荐通过" ? "green" : "orange"}>{selected.match.recommendation}</Tag><p>{selected.match.summary}</p><Typography.Text strong>匹配项</Typography.Text><List size="small" dataSource={selected.match.matchedRequirements} renderItem={(x) => <List.Item><CheckCircleOutlined style={{ color: "#16a34a", marginRight: 8 }} />{x.requirement}：{x.reason}</List.Item>} /><Typography.Text strong>缺失和风险</Typography.Text><List size="small" dataSource={[...selected.match.missingRequirements, ...selected.match.riskPoints]} renderItem={(x) => <List.Item><Tag color="orange">待确认</Tag>{x.requirement}：{x.reason}</List.Item>} /></> : <Empty description="尚未执行匹配" /> }, { key: "review", label: "人工复核", children: <ReviewPanel record={selected} onReview={review} onTransfer={transfer} /> }]} />}</Drawer>
    <Modal title="岗位 JD 管理" open={jobModal} onCancel={() => setJobModal(false)} onOk={() => { if (!jobText.trim()) return message.error("请输入 JD 内容"); const next: JobDescription = { id: `J-${Date.now()}`, jobName: jobText.trim().slice(0, 18), projectName: "新项目", requiredEducation: "本科", preferredMajors: [], requiredSkills: ["数据标注"], preferredSkills: [], minWorkYears: 0, freshGraduateAccepted: true, status: "启用", originalText: jobText.trim(), updatedAt: new Date().toISOString().slice(0, 10) }; setJobs((list) => [...list, next]); setJobId(next.id); setJobText(""); setJobModal(false); message.success("JD 已保存") }}><List dataSource={jobs} renderItem={(item) => <List.Item actions={[<Button type="link" onClick={() => { setJobId(item.id); setJobModal(false); }}>使用</Button>]}>{item.jobName} · {item.status}</List.Item>} /><Input.TextArea value={jobText} onChange={(e) => setJobText(e.target.value)} rows={4} placeholder="粘贴新的岗位 JD 原文" /></Modal>
  </div>;
}

function ReviewPanel({ record, onReview, onTransfer }: { record: ResumeFileRecord; onReview: (status: ResumeReviewStatus, note: string) => void; onTransfer: () => void }) {
  const [note, setNote] = useState(record.manualNote || "");
  return <Space direction="vertical" style={{ width: "100%" }}><Alert type="info" message="AI 仅提供辅助意见，不会自动淘汰候选人。" /><Input.TextArea rows={4} value={note} onChange={(e) => setNote(e.target.value)} placeholder="人工复核备注（不通过时必填）" /><Space wrap>{(["简历通过", "待补充信息", "暂缓", "简历不通过"] as ResumeReviewStatus[]).map((status) => <Button key={status} danger={status === "简历不通过"} type={record.manualReviewStatus === status ? "primary" : "default"} onClick={() => onReview(status, note)}>{status}</Button>)}<Button type="primary" disabled={record.manualReviewStatus !== "简历通过"} onClick={onTransfer}>流转到候选人管理</Button></Space></Space>;
}
