import { ArrowLeftOutlined, PlusOutlined, ReloadOutlined } from "@ant-design/icons";
import { Button, Card, Form, Input, Layout, Modal, Select, Space, Switch, Table, Tag, Typography, message } from "antd";
import { useCallback, useEffect, useState } from "react";
import { api } from "../api/backend";
import { roleLabels, useAuth, type UserRole } from "../auth/AuthContext";

interface ManagedUser { id: string; email: string; name: string; role: UserRole; supplierId: string | null; supplierName: string | null; status: "ACTIVE" | "INACTIVE"; lastLoginAt?: string }
const navigate = (url: string) => { history.pushState({}, "", url); window.dispatchEvent(new PopStateEvent("popstate")); };
export default function UserManagementPage() {
  const { user } = useAuth(); const [rows, setRows] = useState<ManagedUser[]>([]), [suppliers, setSuppliers] = useState<any[]>([]), [loading, setLoading] = useState(false), [open, setOpen] = useState(false); const [form] = Form.useForm();
  const load = useCallback(async () => { setLoading(true); try { const [users, supplierRows] = await Promise.all([api<ManagedUser[]>("/api/auth/users"), api<any[]>("/api/auth/suppliers")]); setRows(users); setSuppliers(supplierRows); } catch (e) { message.error((e as Error).message); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const create = async () => { const values = await form.validateFields(); await api("/api/auth/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); message.success("账号已创建"); setOpen(false); form.resetFields(); void load(); };
  const toggle = async (record: ManagedUser, checked: boolean) => { await api(`/api/auth/users/${record.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: checked ? "ACTIVE" : "INACTIVE" }) }); message.success("账号状态已更新"); void load(); };
  const allowedRoles = user?.role === "PLATFORM_ADMIN" ? Object.keys(roleLabels) as UserRole[] : ["SUPPLIER_VIDEO_RECRUITER", "SUPPLIER_AUDIO_RECRUITER", "SUPPLIER_RECRUITER"] as UserRole[];
  return <Layout className="auto-dashboard-page"><header className="auto-page-header"><div><Typography.Title level={2}>供应商账号管理</Typography.Title><Typography.Text type="secondary">创建账号、绑定供应商并控制启用状态</Typography.Text></div><Space><Button icon={<ArrowLeftOutlined />} onClick={() => navigate("/")}>返回首页</Button><Button icon={<ReloadOutlined />} onClick={() => void load()}>刷新</Button><Button type="primary" icon={<PlusOutlined />} onClick={() => setOpen(true)}>新增账号</Button></Space></header><main className="auto-page-content"><Card><Table rowKey="id" loading={loading} dataSource={rows} pagination={{ pageSize: 20 }} columns={[{ title: "姓名", dataIndex: "name" }, { title: "邮箱", dataIndex: "email" }, { title: "角色", dataIndex: "role", render: (v: UserRole) => <Tag>{roleLabels[v]}</Tag> }, { title: "供应商", dataIndex: "supplierName", render: (v) => v || "全部供应商" }, { title: "最后登录", dataIndex: "lastLoginAt", render: (v) => v ? new Date(v).toLocaleString() : "—" }, { title: "启用", render: (_, r) => <Switch checked={r.status === "ACTIVE"} disabled={r.id === user?.id} onChange={(v) => void toggle(r, v)} /> }]} /></Card></main><Modal title="新增账号" open={open} onCancel={() => setOpen(false)} onOk={() => void create()} okText="创建"><Form form={form} layout="vertical"><Form.Item name="name" label="姓名" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="email" label="邮箱" rules={[{ required: true, type: "email" }]}><Input /></Form.Item><Form.Item name="password" label="初始密码" rules={[{ required: true, min: 8 }]}><Input.Password /></Form.Item><Form.Item name="role" label="角色" rules={[{ required: true }]}><Select options={allowedRoles.map((value) => ({ value, label: roleLabels[value] }))} /></Form.Item>{user?.role === "PLATFORM_ADMIN" && <Form.Item noStyle shouldUpdate={(a, b) => a.role !== b.role}>{({ getFieldValue }) => ["SUPPLIER_ADMIN", "SUPPLIER_VIDEO_RECRUITER", "SUPPLIER_AUDIO_RECRUITER", "SUPPLIER_RECRUITER"].includes(getFieldValue("role")) ? <Form.Item name="supplierId" label="所属供应商" rules={[{ required: true }]}><Select options={suppliers.map((s) => ({ value: s.id, label: s.name }))} /></Form.Item> : null}</Form.Item>}</Form></Modal></Layout>;
}
