import * as XLSX from "xlsx";
import type { Candidate, CandidateStatus } from "../types/recruitment";
import type { CandidateImportRow, ImportContext, ImportDuplicateResult } from "../types/candidateImport";

export const candidateFieldAliases:Record<string,string[]>={name:["候选人姓名","姓名","名字","candidate_name","name"],phone:["手机号","手机号码","联系电话","电话","phone","mobile"],email:["邮箱","电子邮箱","email"],vendor:["供应商","供应商名称","外包公司","vendor"],project:["所属项目","项目","项目名称","project"],position:["应聘岗位","岗位","职位","岗位名称","position"],university:["大学","毕业院校","学校","院校","university"],major:["专业","所学专业","major"],highestEducation:["最高学历","学历","education"],graduationYear:["毕业年份","毕业年","graduation_year"],isFreshGraduate:["是否应届生","应届生","fresh_graduate"],resumeSubmitDate:["简历提交日期","提交日期","投递日期"],resumeResult:["简历筛选结果","简历结果","筛选结果"],currentStatus:["当前状态","候选人状态","招聘状态"],interviewDate:["面试日期","面试时间"],interviewRound:["面试轮次","轮次"],interviewResult:["面试结果","面试结论"],interviewer:["面试官"],expectedEntryDate:["预计入职日期","预计到岗日期"],actualEntryDate:["实际入职日期","实际到岗日期"],remark:["备注","说明"],updatedBy:["更新人","操作人"]};
const clean=(value:unknown)=>String(value??"").trim().normalize("NFKC").replace(/[ \t]+/g," ")||undefined;
export const parseBoolean=(value:unknown)=>{const v=String(value??"").trim().toLowerCase();if(["是","y","yes","true","1"].includes(v))return true;if(["否","n","no","false","0"].includes(v))return false;return undefined};
export function parseDate(value:unknown):string|undefined{if(value===undefined||value===null||value==="")return undefined;if(typeof value==="number"){const d=XLSX.SSF.parse_date_code(value);return d?`${d.y}-${String(d.m).padStart(2,"0")}-${String(d.d).padStart(2,"0")}${d.H?` ${String(d.H).padStart(2,"0")}:${String(d.M).padStart(2,"0")}`:""}`:undefined}let s=String(value).trim().replace(/[年/.]/g,"-").replace(/月/g,"-").replace(/日/g,"");if(/^\d{2}-\d{2}$/.test(s))s=`2026-${s}`;const date=new Date(s);return Number.isNaN(date.getTime())?undefined:`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}${s.includes(":")?` ${s.split(" ")[1]}`:""}`}
export function mapHeaders(headers:string[]){const mapping:Record<string,string|undefined>={};headers.forEach((header,index)=>{const normalized=header.trim().toLowerCase();const key=Object.entries(candidateFieldAliases).find(([,aliases])=>aliases.some(alias=>alias.toLowerCase()===normalized))?.[0];if(key)mapping[key]=String(index)});return mapping}
export function rowsFromSheet(sheet:XLSX.WorkSheet):{headers:string[];rows:unknown[][]}{const values=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,defval:"",raw:true});const first=values.findIndex((row)=>row.some((cell)=>String(cell??"").trim()));return first<0?{headers:[],rows:[]}: {headers:(values[first]||[]).map((x)=>String(x??"")),rows:values.slice(first+1)};}
export function toImportRows(rows:unknown[][],mapping:Record<string,string|undefined>):CandidateImportRow[]{return rows.map((source,index)=>{const get=(key:string)=>mapping[key]===undefined?undefined:source[Number(mapping[key]!)];return {rowNumber:index+2,name:clean(get("name")),phone:clean(get("phone"))?.replace(/[\s-]/g,"").replace(/^\+?86/,""),email:clean(get("email"))?.toLowerCase(),vendor:clean(get("vendor")),project:clean(get("project")),position:clean(get("position")),university:clean(get("university")),major:clean(get("major")),highestEducation:clean(get("highestEducation")),graduationYear:Number(get("graduationYear"))||undefined,isFreshGraduate:parseBoolean(get("isFreshGraduate")),resumeSubmitDate:parseDate(get("resumeSubmitDate")),resumeResult:clean(get("resumeResult")),currentStatus:clean(get("currentStatus")),interviewDate:parseDate(get("interviewDate")),interviewRound:clean(get("interviewRound")),interviewResult:clean(get("interviewResult")),interviewer:clean(get("interviewer")),expectedEntryDate:parseDate(get("expectedEntryDate")),actualEntryDate:parseDate(get("actualEntryDate")),remark:clean(get("remark")),updatedBy:clean(get("updatedBy")),validationStatus:"待校验",errors:[],warnings:[],action:"创建为新候选人"};})}
const statusAliases:Record<string,CandidateStatus>={待约面:"待安排面试",约面中:"待面试",通过待入职:"待入职",已到岗:"培训中",在项目:"项目中"};
// @ts-ignore 动态字段校验
export function validateCandidateImportRow(row:CandidateImportRow,context:ImportContext){const next={...row,errors:[],warnings:[]};if(!next.name)next.errors.push("姓名不能为空");if(!next.vendor)next.errors.push("供应商不能为空");if(!next.position)next.errors.push("岗位不能为空");if(next.phone&&!/^1[3-9]\d{9}$/.test(next.phone))next.errors.push("手机号格式不合法");if(next.email&&!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(next.email))next.errors.push("邮箱格式不合法");if(next.graduationYear&&(next.graduationYear<1980||next.graduationYear>2035))next.errors.push("毕业年份不合理");if(next.resumeSubmitDate&&next.actualEntryDate&&next.actualEntryDate<next.resumeSubmitDate)next.errors.push("实际入职日期早于简历提交日期");if(next.interviewDate&&next.expectedEntryDate&&next.expectedEntryDate<next.interviewDate.slice(0,10))next.warnings.push("预计入职日期早于面试日期");if(next.vendor&&!context.vendors.includes(next.vendor))next.warnings.push("供应商不在系统列表中，可确认后创建");if(next.position&&!context.positions.includes(next.position))next.warnings.push("岗位不在系统列表中，可确认后创建");if(next.currentStatus&&statusAliases[next.currentStatus])next.currentStatus=statusAliases[next.currentStatus];if(next.currentStatus&&!context.statuses.includes(next.currentStatus))next.errors.push(`无法识别状态：${next.currentStatus}`);if(!next.phone&&!next.email)next.warnings.push("手机号和邮箱均缺失");next.validationStatus=next.errors.length?"校验失败":next.warnings.length?"警告":"校验通过";return next}
// @ts-ignore 动态重复匹配
export function detectImportDuplicate(row:CandidateImportRow,context:ImportContext):ImportDuplicateResult{const sameName=(context.existing.filter((c)=>c.name===row.name).map((c)=>({id:c.id,phone:c.phone,university:(c as Candidate&{university?:string}).university,major:(c as Candidate&{major?:string}).major}))).concat(context.batch.filter((r)=>r!==row&&r.name===row.name).map((r)=>({id:"",phone:r.phone,university:r.university,major:r.major,row:r.rowNumber})));if(!sameName.length)return{level:"无重复",matchedCandidateIds:[],matchedImportRows:[],reasons:[]};const exact=sameName.filter((x)=>row.phone&&x.phone&&row.phone===x.phone||row.email&&x.email===row.email);if(exact.length)return{level:"确定重复",matchedCandidateIds:exact.map((x)=>x.id).filter(Boolean),matchedImportRows:exact.map((x)=>x.row).filter(Boolean),reasons:["姓名与完整手机号一致"]};const sameSchool=sameName.filter((x)=>row.university&&x.university&&row.university===x.university&&row.major&&x.major&&row.major===x.major);if(sameSchool.length)return{level:"高度疑似重复",matchedCandidateIds:sameSchool.map((x)=>x.id).filter(Boolean),matchedImportRows:sameSchool.map((x)=>x.row).filter(Boolean),reasons:["姓名、大学、专业存在一致"]};if(sameName.some((x)=>x.university&&row.university&&x.university!==row.university))return{level:"同名不同人",matchedCandidateIds:sameName.map((x)=>x.id).filter(Boolean),matchedImportRows:sameName.map((x)=>x.row).filter(Boolean),reasons:["姓名相同但大学不同"]};return{level:row.university?"疑似重复":"需人工复核",matchedCandidateIds:sameName.map((x)=>x.id).filter(Boolean),matchedImportRows:sameName.map((x)=>x.row).filter(Boolean),reasons:["姓名相同，身份信息不足"]}}
export function createCandidateFromImport(row:CandidateImportRow):Candidate{const now=new Date().toISOString().slice(0,16).replace("T"," ");const status=(row.currentStatus||"简历待筛选") as CandidateStatus;return{id:`C-IMP-${Date.now()}-${row.rowNumber}`,name:row.name||"未命名",phone:row.phone||"",vendor:row.vendor||"未设置供应商",project:row.project||"未设置项目",position:row.position||"未设置岗位",resumeSubmitDate:row.resumeSubmitDate||now.slice(0,10),resumeResult:row.resumeResult==="不通过"?"不通过":row.resumeResult==="通过"?"通过":"待筛选",resumeFeedbackDate:undefined,interviewScheduled:Boolean(row.interviewDate),interviewDate:row.interviewDate,interviewRound:row.interviewRound,interviewer:row.interviewer,interviewResult:row.interviewResult as Candidate["interviewResult"],interviews:[],offerConfirmed:["待入职","培训中","项目中"].includes(status),expectedEntryDate:row.expectedEntryDate,actualEntryDate:row.actualEntryDate,currentStatus:status,updatedAt:now,updatedBy:row.updatedBy||"Excel导入",timeline:[{time:now,action:"通过 Excel 批量导入候选人",operator:row.updatedBy||"Excel导入",remark:row.remark}],statusEvents:[{id:`SE-IMP-${Date.now()}-${row.rowNumber}`,candidateId:"",status,effectiveAt:now,operator:row.updatedBy||"Excel导入",source:"系统",remark:"Excel批量导入"}],operationLogs:[{id:`LOG-IMP-${Date.now()}-${row.rowNumber}`,candidateId:"",module:"系统",action:"通过 Excel 批量导入候选人",operator:row.updatedBy||"Excel导入",operatedAt:now,reason:row.remark}],};}
export function downloadImportTemplate(withExamples=true){const headers=["候选人姓名","手机号","邮箱","供应商","所属项目","应聘岗位","大学","专业","最高学历","毕业年份","是否应届生","简历提交日期","简历筛选结果","当前状态","面试日期","面试轮次","面试结果","面试官","预计入职日期","实际入职日期","备注","更新人"];const examples=withExamples?[["张三","13812344521","zhangsan@example.com","人瑞","多模态数据项目","视频评测工程师","山东大学","计算机科学与技术","本科",2025,"否","2026-08-01","通过","待面试","2026-08-03 14:00","第一轮","待反馈","Kim","2026-08-04","","待确认面试时间","招聘专员"],["李四","18634567826","lisi@example.com","供应商B","Caption 数据项目","Caption 标注员","青岛大学","汉语言文学","本科",2026,"是","2026-08-01","通过","待安排面试","","","","","","","","供应商HR"]]:[];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([headers,...examples]),"候选人导入模板");const fileName=withExamples?"候选人导入模板_示例.xlsx":"候选人导入模板_空白.xlsx";XLSX.writeFile(wb,fileName,{bookType:"xlsx",compression:true})}
